[package]
name = "prob13_1"
version = "0.1.0"
authors = ["of9 <of9@st-andrews.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "0.1.0"